import { chromium } from 'playwright-core'
const browser = await chromium.launch({ channel: 'msedge', headless: true })
const ctx = await browser.newContext({ viewport: { width: 393, height: 852 }, isMobile: true, hasTouch: true })
const page = await ctx.newPage()
await page.goto('http://localhost:1430/', { waitUntil: 'networkidle' })
await page.evaluate(() => localStorage.setItem('agent-im-server', 'http://127.0.0.1:8011'))
await page.goto('http://localhost:1430/#/login', { waitUntil: 'networkidle' })
const inputs = page.locator('.field input')
await inputs.nth(0).fill('mobile')
await inputs.nth(1).fill('agent-flow')
await page.click('.btn-primary')
await page.waitForTimeout(2000)
await page.screenshot({ path: '/tmp/shot-home.png' })
await page.locator('.card-line.pressable').first().click()
await page.waitForTimeout(1400)
await page.screenshot({ path: '/tmp/shot-picker.png' })
await page.click('text=移动端测试会话')
await page.waitForTimeout(1600)
await page.screenshot({ path: '/tmp/shot-chat2.png' })
await browser.close()
